//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvPayment
    {
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public string PaperNo { get; set; }
        public Nullable<System.DateTime> PaperDate { get; set; }
        public string ContractorRep { get; set; }
        public Nullable<int> ContractorRepPosition { get; set; }
        public Nullable<double> PayValue { get; set; }
        public string PayContent { get; set; }
        public string RequestDocumentNo { get; set; }
        public string TaxCode { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Contractor_id { get; set; }
        public Nullable<int> Contract_id { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
