//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttFile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string TomLuocND { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> HolderId { get; set; }
    }
}
