//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiddingProfile
    {
        public int Id { get; set; }
        public Nullable<double> BidValue { get; set; }
        public Nullable<System.DateTime> BidTime { get; set; }
        public string BidComer { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<System.DateTime> IdentityIssueDate { get; set; }
        public string IdentityIssueLocation { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BidPack_id { get; set; }
        public Nullable<int> Contractor_id { get; set; }
        public string RepName { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactPosition { get; set; }
    
        public virtual BidPack BidPack { get; set; }
        public virtual Contractor Contractor { get; set; }
    }
}
