//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidPack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BidPack()
        {
            this.BiddingProfile = new HashSet<BiddingProfile>();
            this.WinContractor = new HashSet<WinContractor>();
            this.BidPackBudget = new HashSet<BidPackBudget>();
        }
    
        public int TaskProgress_id { get; set; }
        public string BidPackNo { get; set; }
        public string BidHolder { get; set; }
        public string SponsorRep { get; set; }
        public string ConsultRep { get; set; }
        public string ConsultRepPosition { get; set; }
        public Nullable<System.DateTime> BidStart { get; set; }
        public Nullable<System.DateTime> BidClose { get; set; }
        public string TaskContent { get; set; }
        public string BidLocation { get; set; }
        public string AppealLocation { get; set; }
        public string ContactName { get; set; }
        public string ContactPosition { get; set; }
        public string ContactPhone { get; set; }
        public string ContactDepartment { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public Nullable<int> ContractDurationUnit { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public string BidEvaluatingMethod { get; set; }
        public Nullable<int> Status { get; set; }
        public string SponsorRepPosition { get; set; }
        public string BidMethod { get; set; }
        public string ProjectName { get; set; }
        public string LoaiTien { get; set; }
        public Nullable<double> TyGia { get; set; }
        public string ContractType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiddingProfile> BiddingProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WinContractor> WinContractor { get; set; }
        public virtual TaskProgress TaskProgress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidPackBudget> BidPackBudget { get; set; }
    }
}
