//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidPackBudget
    {
        public int Id { get; set; }
        public string BudgetName { get; set; }
        public Nullable<double> BudgetRate { get; set; }
        public Nullable<double> BudgetValue { get; set; }
        public Nullable<int> BidPack_Id { get; set; }
    
        public virtual BidPack BidPack { get; set; }
    }
}
