//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contractor()
        {
            this.AdvPayment = new HashSet<AdvPayment>();
            this.BiddingProfile = new HashSet<BiddingProfile>();
            this.WinContractor = new HashSet<WinContractor>();
            this.Handover = new HashSet<Handover>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string RepName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string BankAccNo { get; set; }
        public string BankName { get; set; }
        public string TaxNo { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string EmailContact { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> OrderingNo { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<double> WinPrice { get; set; }
        public string BankAccNoUSD { get; set; }
        public string BankNameUSD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvPayment> AdvPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiddingProfile> BiddingProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WinContractor> WinContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Handover> Handover { get; set; }
    }
}
