//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.AdvPayment = new HashSet<AdvPayment>();
            this.Settlement = new HashSet<Settlement>();
            this.ContractItem = new HashSet<ContractItem>();
        }
    
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public string ContractName { get; set; }
        public string ContractContent { get; set; }
        public string ContractSupervisor { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<System.DateTime> EffectedDate { get; set; }
        public Nullable<int> ContractDuration { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> ContractCompletedDate { get; set; }
        public string ContractValue { get; set; }
        public Nullable<int> ContractStatus { get; set; }
        public string ARepDepartment { get; set; }
        public string ARepName { get; set; }
        public string ARepPosition { get; set; }
        public string ARepAddress { get; set; }
        public string ARepPhone { get; set; }
        public string ARepFax { get; set; }
        public string ARepEmail { get; set; }
        public string ARepTaxNo { get; set; }
        public string ARepBankAccountNo { get; set; }
        public string ARepBankName { get; set; }
        public string BRepDepartment { get; set; }
        public string BRepName { get; set; }
        public string BRepPosition { get; set; }
        public string BRepAddress { get; set; }
        public string BARepPhone { get; set; }
        public string BRepFax { get; set; }
        public string BRepTaxNo { get; set; }
        public string BRepBankAccountNo { get; set; }
        public string BRepBankName { get; set; }
        public string BContactName { get; set; }
        public string BContactPhone { get; set; }
        public string BRepEmail { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public Nullable<int> ProgressId { get; set; }
        public Nullable<int> BidPackId { get; set; }
        public Nullable<int> ContractTimeUnit { get; set; }
        public string ContractStatusName { get; set; }
        public string CreatedUserCode { get; set; }
        public string LoaiTien { get; set; }
        public Nullable<double> TyGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvPayment> AdvPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settlement> Settlement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractItem> ContractItem { get; set; }
    }
}
