//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Handover = new HashSet<Handover>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string PhienHieu { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> OrderingNo { get; set; }
        public Nullable<int> Status { get; set; }
        public string RepName { get; set; }
        public string RepPosition { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string RepEmail { get; set; }
        public string TaxNo { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Handover> Handover { get; set; }
    }
}
