//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Handover
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Handover()
        {
            this.HandoverItem = new HashSet<HandoverItem>();
        }
    
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public string PaperNo { get; set; }
        public Nullable<System.DateTime> PaperDate { get; set; }
        public string ContractorId { get; set; }
        public string ContractorRepName { get; set; }
        public string ContractorRepPosition { get; set; }
        public string Location { get; set; }
        public string Content { get; set; }
        public string RevDepartmentId { get; set; }
        public string RevRepresentativeId { get; set; }
        public string RevRepresentative { get; set; }
        public string RevRepresentativePosition { get; set; }
        public string RevContactId { get; set; }
        public string RevContact { get; set; }
        public string RevContactPosition { get; set; }
        public string RevContactPhone { get; set; }
        public string RevContactEmail { get; set; }
        public string RevPerson1 { get; set; }
        public string RevPerson1Pos { get; set; }
        public string RevPerson2 { get; set; }
        public string RevPerson2Pos { get; set; }
        public string RevPerson3 { get; set; }
        public string RevPerson3Pos { get; set; }
        public string RevPerson4 { get; set; }
        public string RevPerson4Pos { get; set; }
        public string RevPerson5 { get; set; }
        public string RevPerson5Pos { get; set; }
        public string GivDepartmentId { get; set; }
        public string GivPerson1 { get; set; }
        public string GivPerson1Pos { get; set; }
        public string GivPerson2 { get; set; }
        public string GivPerson2Pos { get; set; }
        public string GivPerson3 { get; set; }
        public string GivPerson3Pos { get; set; }
        public string GivContact { get; set; }
        public string GivContactPhone { get; set; }
        public string GivContactEmail { get; set; }
        public Nullable<int> RevParty_id { get; set; }
        public Nullable<int> GivParty_id { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HandoverItem> HandoverItem { get; set; }
    }
}
