//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandoverItem
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ProducerId { get; set; }
        public string OriginCountryId { get; set; }
        public string UnitId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Handover_id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Handover Handover { get; set; }
    }
}
