//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> OperationType { get; set; }
        public string OperationNote { get; set; }
        public Nullable<int> Type { get; set; }
        public string LogObjectCode { get; set; }
        public string Content { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string CommentedBy { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> LogObjectId { get; set; }
    }
}
