//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectBudget = new HashSet<ProjectBudget>();
            this.PMMember = new HashSet<PMMember>();
        }
    
        public int TaskProgress_id { get; set; }
        public string Code { get; set; }
        public Nullable<int> ProjectGroupId { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string SponsorName { get; set; }
        public string HolderName { get; set; }
        public string ConsultName { get; set; }
        public string Objective { get; set; }
        public string InvestContent { get; set; }
        public string Location { get; set; }
        public string CertNo { get; set; }
        public string CertDate { get; set; }
        public string CertAuthority { get; set; }
        public string DeliveringDate { get; set; }
        public string GroundArea { get; set; }
        public string ContractMethod { get; set; }
        public Nullable<double> TotalInvest { get; set; }
        public string InvestSupport { get; set; }
        public string InvestCondition { get; set; }
        public string PStatus { get; set; }
        public string Phase { get; set; }
        public Nullable<int> Status { get; set; }
        public string DecisionName { get; set; }
        public Nullable<int> DecisionId { get; set; }
        public Nullable<int> SponsorId { get; set; }
        public Nullable<int> HolderId { get; set; }
        public Nullable<int> ConsultId { get; set; }
        public Nullable<int> ContractMethodId { get; set; }
        public Nullable<int> PStatusId { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public string DecisionCode { get; set; }
        public string SponsorCode { get; set; }
        public string HolderCode { get; set; }
        public string ConsultCode { get; set; }
        public string CreatedUserCode { get; set; }
        public string CreatedUserName { get; set; }
        public string LoaiTien { get; set; }
        public Nullable<double> TyGia { get; set; }
        public Nullable<double> TotalEstimatedCost { get; set; }
        public Nullable<double> ManageCost { get; set; }
        public Nullable<double> RedundantCost { get; set; }
        public Nullable<double> OtherCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudget> ProjectBudget { get; set; }
        public virtual TaskProgress TaskProgress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMMember> PMMember { get; set; }
    }
}
