//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PTask()
        {
            this.PMMember = new HashSet<PMMember>();
        }
    
        public int TaskProgress_id { get; set; }
        public string Description { get; set; }
        public string TaskContent { get; set; }
        public string Priority { get; set; }
        public string TaskStatus { get; set; }
        public string Code { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> TaskStatusId { get; set; }
        public Nullable<int> PTaskStatusId { get; set; }
        public string CreatedUserCode { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
    
        public virtual TaskProgress TaskProgress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMMember> PMMember { get; set; }
    }
}
