//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class A77_1004 : DbContext
    {
        public A77_1004()
            : base("name=A77_1004")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvPayment> AdvPayment { get; set; }
        public virtual DbSet<AttFile> AttFile { get; set; }
        public virtual DbSet<BiddingProfile> BiddingProfile { get; set; }
        public virtual DbSet<BidPack> BidPack { get; set; }
        public virtual DbSet<BidPackBudget> BidPackBudget { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryType> CategoryType { get; set; }
        public virtual DbSet<CauHinhHeThong> CauHinhHeThong { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<ContractItem> ContractItem { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DonVi> DonVi { get; set; }
        public virtual DbSet<GoodsCategory> GoodsCategory { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Handover> Handover { get; set; }
        public virtual DbSet<HandoverItem> HandoverItem { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<MenuChucNang> MenuChucNang { get; set; }
        public virtual DbSet<NhomHSTL> NhomHSTL { get; set; }
        public virtual DbSet<PMMember> PMMember { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectBudget> ProjectBudget { get; set; }
        public virtual DbSet<ProjectGroup> ProjectGroup { get; set; }
        public virtual DbSet<PTask> PTask { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Settlement> Settlement { get; set; }
        public virtual DbSet<SettlementItem> SettlementItem { get; set; }
        public virtual DbSet<SharingGroup> SharingGroup { get; set; }
        public virtual DbSet<TaskComment> TaskComment { get; set; }
        public virtual DbSet<TaskProgress> TaskProgress { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VanBan> VanBan { get; set; }
        public virtual DbSet<WinContractor> WinContractor { get; set; }
        public virtual DbSet<Group_User> Group_User { get; set; }
        public virtual DbSet<Token> Token { get; set; }
    
        public virtual ObjectResult<Get_Configs_Result> Get_Configs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Configs_Result>("Get_Configs");
        }
    
        public virtual ObjectResult<Get_DanhSachDuAnCham_Result> Get_DanhSachDuAnCham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachDuAnCham_Result>("Get_DanhSachDuAnCham");
        }
    
        public virtual ObjectResult<Get_Danhsachduanchamtiendo_Result> Get_Danhsachduanchamtiendo(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Danhsachduanchamtiendo_Result>("Get_Danhsachduanchamtiendo", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachDuAnTheoLoai_Result> Get_DanhSachDuAnTheoLoai(Nullable<int> projectTypeId, Nullable<int> projectTypeValue)
        {
            var projectTypeIdParameter = projectTypeId.HasValue ?
                new ObjectParameter("ProjectTypeId", projectTypeId) :
                new ObjectParameter("ProjectTypeId", typeof(int));
    
            var projectTypeValueParameter = projectTypeValue.HasValue ?
                new ObjectParameter("ProjectTypeValue", projectTypeValue) :
                new ObjectParameter("ProjectTypeValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachDuAnTheoLoai_Result>("Get_DanhSachDuAnTheoLoai", projectTypeIdParameter, projectTypeValueParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachGoiThauByProjectId_Result> Get_DanhSachGoiThauByProjectId(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachGoiThauByProjectId_Result>("Get_DanhSachGoiThauByProjectId", projectIdParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachGoiThauTrungThau_Result> Get_DanhSachGoiThauTrungThau(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachGoiThauTrungThau_Result>("Get_DanhSachGoiThauTrungThau", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachHopDongByProjectId_Result> Get_DanhSachHopDongByProjectId(Nullable<int> projectId)
        {
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachHopDongByProjectId_Result>("Get_DanhSachHopDongByProjectId", projectIdParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachHopDongChamTienDo_Result> Get_DanhSachHopDongChamTienDo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachHopDongChamTienDo_Result>("Get_DanhSachHopDongChamTienDo");
        }
    
        public virtual ObjectResult<Get_DanhSachNhaThauByBidPackId_Result> Get_DanhSachNhaThauByBidPackId(Nullable<int> bidPackId)
        {
            var bidPackIdParameter = bidPackId.HasValue ?
                new ObjectParameter("BidPackId", bidPackId) :
                new ObjectParameter("BidPackId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachNhaThauByBidPackId_Result>("Get_DanhSachNhaThauByBidPackId", bidPackIdParameter);
        }
    
        public virtual ObjectResult<Get_DanhSachQuyetToanHD_Result> Get_DanhSachQuyetToanHD(Nullable<int> contractId)
        {
            var contractIdParameter = contractId.HasValue ?
                new ObjectParameter("ContractId", contractId) :
                new ObjectParameter("ContractId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_DanhSachQuyetToanHD_Result>("Get_DanhSachQuyetToanHD", contractIdParameter);
        }
    
        public virtual ObjectResult<Get_List_Samples_Result> Get_List_Samples(ObjectParameter totalRecord)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_List_Samples_Result>("Get_List_Samples", totalRecord);
        }
    
        public virtual ObjectResult<Get_TienDoDuAn_Result> Get_TienDoDuAn(Nullable<long> projectID)
        {
            var projectIDParameter = projectID.HasValue ?
                new ObjectParameter("ProjectID", projectID) :
                new ObjectParameter("ProjectID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TienDoDuAn_Result>("Get_TienDoDuAn", projectIDParameter);
        }
    }
}
