//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementItem
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> SLTheoHD { get; set; }
        public Nullable<int> SLThucHienLuyKeKyTruoc { get; set; }
        public Nullable<int> SLThucHienKyNay { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> CostTheoHD { get; set; }
        public Nullable<double> PaidLuyKeKyTruoc { get; set; }
        public Nullable<double> PaidKyNay { get; set; }
        public string Note { get; set; }
        public Nullable<int> Settlement_id { get; set; }
        public string UnitName { get; set; }
    
        public virtual Settlement Settlement { get; set; }
    }
}
