//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Settlement()
        {
            this.SettlementItem = new HashSet<SettlementItem>();
        }
    
        public int Id { get; set; }
        public string PaperNo { get; set; }
        public Nullable<System.DateTime> PaperDate { get; set; }
        public string ProjectName { get; set; }
        public string BidPackName { get; set; }
        public string ContractNo { get; set; }
        public string SettlementNumber { get; set; }
        public string PayeeName { get; set; }
        public string ReceivingName { get; set; }
        public Nullable<double> TotalValue { get; set; }
        public Nullable<double> RetakingCost { get; set; }
        public Nullable<double> PaidKLHTDenCuoiKy { get; set; }
        public Nullable<double> CostLuyKeGTTHDenCuoiKy { get; set; }
        public Nullable<double> DiscountTamUng { get; set; }
        public Nullable<double> PaidKyNay { get; set; }
        public Nullable<double> PaidTamUng { get; set; }
        public Nullable<double> PaidKhoiLuong { get; set; }
        public Nullable<double> PaidLuyKe { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Contract_id { get; set; }
        public string BaseDecision { get; set; }
    
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettlementItem> SettlementItem { get; set; }
    }
}
