//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskProgress()
        {
            this.TaskProgress1 = new HashSet<TaskProgress>();
            this.TaskProgress11 = new HashSet<TaskProgress>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Duration { get; set; }
        public string DurationUnit { get; set; }
        public Nullable<int> PercentDone { get; set; }
        public string ConstraintType { get; set; }
        public Nullable<System.DateTime> ConstraintDate { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> Leaf { get; set; }
        public Nullable<int> PrevTaskId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual BidPack BidPack { get; set; }
        public virtual Project Project { get; set; }
        public virtual PTask PTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProgress> TaskProgress1 { get; set; }
        public virtual TaskProgress TaskProgress2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProgress> TaskProgress11 { get; set; }
        public virtual TaskProgress TaskProgress3 { get; set; }
    }
}
