//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBan
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CapCongVan { get; set; }
        public string SoCongVan { get; set; }
        public Nullable<System.DateTime> NgayCongVan { get; set; }
        public string TomLuocND { get; set; }
        public string NguoiKy { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> NhomHSTLId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> Owner_id { get; set; }
        public Nullable<int> SharingGroup_id { get; set; }
    
        public virtual SharingGroup SharingGroup { get; set; }
        public virtual User User { get; set; }
    }
}
